apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "frontend-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "frontend"
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "profile-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "profile"
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "recommendation-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "recommendation"
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "user-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "user"
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "reservation-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "reservation"
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "search-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "search"
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "geo-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "geo"
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "rate-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "rate"
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70